# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build Windows
      run: GOOS=windows GOARCH=amd64 output_name=car_manager_win go build -o ./car_manager_win mariapori.fi/hello
    - name: Build Linux
      run: GOOS=linux GOARCH=amd64 output_name=car_manager_linux go build -o ./car_manager_linux mariapori.fi/hello
    
    - name: Upload a Build Artifact Windows
      uses: actions/upload-artifact@v3.1.2
      with:
        name: car_manager_win
        path: car_manager_win.exe
        
    - name: Upload a Build Artifact Linux
      uses: actions/upload-artifact@v3.1.2
      with:
        name: car_manager_linux
        path: car_manager_linux
    
